name: Deploy INT2
on:
  pull_request:
  
jobs:
  test-artifacts-list:
    runs-on: ubuntu-latest
    steps:
    - name: listing
      id: list
      uses: yakubique/list-artifacts@v1.1
      env:
        CLUSTER_NAME: gis-team-1
      with:
        name: repo-changes-final-${{ env.CLUSTER_NAME }}
    - name: checking
      id: check
      if: steps.list.outputs.artifacts == ''
      run: echo "yooooo" #echo "${{ steps.list.outputs.result }}"
    - name: Extract US changes
      if: steps.check.outcome == 'success'
      run: echo "ca marche mais normalement ca ne doit pas marcher"
